language: go
go:
  - 1.11.x
  - master

dist: xenial
sudo: no
services:
  - docker

git:
  depth: no

env:
  - GO111MODULE=on

install:
  - env GO111MODULE=off go get github.com/mitchellh/gox
  - go mod download
  - docker pull ansemjo/fpm:alpine

before_script:
  - git tag -n
  - git log --graph --all
  - sh version.sh

script:
  - make test
  - make build
  - make release
  - make packages DOCKER_BIN=docker
