language: go
go:
  - 1.11.x
  - master

dist: xenial
sudo: no
services:
  - docker

git:
  depth: no

env:
  - GO111MODULE=on

install:
  - env GO111MODULE=off go get github.com/mitchellh/gox
  - go mod download

before_script:
  - git fetch --unshallow
  - git tag
  - sh version.sh


script:
  - make test
  - make build
  - make release
  - make packages DOCKER_BIN=docker
