language: go
go:
  - 1.11.x
  - master

dist: xenial
sudo: no
services:
  - docker

env:
  - GO111MODULE=on

install:
  - env GO111MODULE=off go get github.com/mitchellh/gox
  - go mod download
  - docker pull ansemjo/fpm:alpine
  - sh version.sh

script:
  - make test
  - make build
  - make release
  - make packages DOCKER_BIN=docker

deploy:
  provider: releases
  api_key:
    secure: BxRQYMUxvASRCST6C8l+zuBJidj1A58B1pvfnoRsvTPHW49QE1r4iiLy1mMPOmM1f4bhyZZ5HFIZGeqTxaaE0QHvxtS03exXmgTuxcfkmMOtBsXdgvH23bnEQ1O7PncGDq2Tfs3ANrtAHUxOU0Ler78O0WMpOgcv8XOrLuDu8ACYlQ3I+i767T2d/E4y42oRqIDQynxufQAG7GBpQ45rNjSQbxqzXJVHOpGVqBcbs5dSwbFEStWrHhom/wHgKW0vZ56UIvOYVhk+DLmRoT7XpQN4f3FZgUifbe8bEBSv6murzvfvWzgyn9iGFv0uU2E07Pr3DUqtnonxOeRFA+405kUT+OB2VQh6Qby7IxM3+ypmh9AzbO85wL17amoPBN+WB+8WURzfIBA1om8dDVcdxmkLgL7P77614BpFgZ2SlJFqbyu4BP70KTffb0yFDHyE3sa43G1tt2MUAnuceqgeXN1sTwhcj0Dh9jbcPQ20thjXF8G/PsxeInEvg/g7gOx8vavu2ZUj+27wra0ozYDUOOHO1aX5qVfntwTud74cqIvjxIpEQrGxoJMCNpKu9UIAPGgXA0fgCaI8OtwKJKOHiVnYfh9ZdFfyBrnjiox1Ur7v0pO6EM6FrXf/ePYBY7gq0F1pS7bMPifbpk1Kga/V1ARJCvqKQB6Bf65o7wh9/D8=
  file: release/*
  file_glob: yes
  skip_cleanup: yes
  on:
    repo: ansemjo/aenker
    tags: yes
    condition: $TRAVIS_GO_VERSION =~ ^1\.11
