language: go
go:
  - 1.11.x
  - master

sudo: no
git:
  depth: no

env:
  - GO111MODULE=on

install:
  - env GO111MODULE=off go get github.com/mitchellh/gox
  - go mod download

before_script:
  - git tag
  - git describe --always --long

script:
  - make test
  - make build
  - make release
  - make packages DOCKER_BIN=docker
