language: go
go:
  - 1.11.x
    #- master

dist: xenial
sudo: no
services:
  - docker

git:
  depth: no

env:
  - GO111MODULE=on

install:
  - env GO111MODULE=off go get github.com/mitchellh/gox
  - go mod download
    #- docker pull ansemjo/fpm:alpine

before_script:
  - curl -L 'https://pgp.mit.edu/pks/lookup?op=get&search=0x21211F2AE74DE762' | gpg --import
  - curl -L https://keybase.io/ansemjo/pgp_keys.asc | gpg --import
  - git tag -v 0.3.6
  - git tag -v 0.4.0
  - git tag -n
  - sh version.sh

script:
  - make test
  - make build
  - make release
  - make packages DOCKER_BIN=docker
