site_name: ansemjo/aenker
theme: readthedocs
use_directory_urls: false
nav:
  - Home: index.md
  - Specification: SPECIFICATION.md
  - Manual:
    - aenker: aenker.md
    - Encrypt files: aenker_seal.md
    - Decrypt files: aenker_open.md
    - Generate new key: aenker_keygen.md
    - Print public key: aenker_pubkey.md
    - Generate autocompletion: aenker_docs_completion.md
    - Generate manpages: aenker_docs_manual.md
